---
- name: Setup Nginx for Assetrix.ng
  hosts: webservers
  become: yes

  vars:
    domain_name: "Assetrix.ng"
    

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Install Nginx and Certbot
      apt:
        name:
          - nginx
          - python3-certbot-nginx
        state: present

    

    
    - name: Create Nginx server block
      copy:
        dest: "/etc/nginx/sites-available/{{ domain_name }}"
        content: |
          server {
              listen 80;
              server_name {{ domain_name }};
              
              location / {
                proxy_pass http://localhost:3004;
                proxy_buffering off;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_connect_timeout 75s;
              }
            }


    - name: Enable Nginx site
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    # Optional: Enable HTTPS with Certbot
    - name: Obtain SSL certificate with Certbot
      command: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos -m ekwealorleo@gmail.com
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
